// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	RegisterRequest
	RegisterResponse
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// 注册请求包
type RegisterRequest struct {
	Username         *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterRequest) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

// 注册响应包
type RegisterResponse struct {
	ErrorCode        *uint32 `protobuf:"varint,1,req,name=error_code" json:"error_code,omitempty"`
	UserId           *uint64 `protobuf:"varint,2,opt,name=user_id,def=0" json:"user_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_RegisterResponse_UserId uint64 = 0

func (m *RegisterResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *RegisterResponse) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return Default_RegisterResponse_UserId
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "protocol.register_request")
	proto.RegisterType((*RegisterResponse)(nil), "protocol.register_response")
}

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x03, 0x33, 0x84, 0x38, 0x60, 0x7c, 0x25, 0x2f, 0x2e, 0x81, 0xa2,
	0xd4, 0xf4, 0xcc, 0xe2, 0x92, 0xd4, 0xa2, 0xf8, 0xa2, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x29, 0x2e, 0x8e, 0xd2, 0xe2, 0xd4, 0xa2, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x26, 0x0d,
	0xce, 0x20, 0x38, 0x1f, 0x24, 0x57, 0x90, 0x58, 0x5c, 0x5c, 0x9e, 0x5f, 0x94, 0x22, 0xc1, 0x04,
	0x91, 0x83, 0xf1, 0x95, 0xfc, 0xb8, 0x04, 0x91, 0xcc, 0x2a, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15,
	0x92, 0xe5, 0xe2, 0x4a, 0x2d, 0x2a, 0xca, 0x2f, 0x8a, 0x4f, 0xce, 0x4f, 0x81, 0x18, 0xc7, 0x1b,
	0xc4, 0x09, 0x16, 0x71, 0x06, 0x0a, 0x00, 0xcd, 0x63, 0x07, 0x99, 0x1d, 0x9f, 0x09, 0x32, 0x8e,
	0x51, 0x83, 0xc5, 0x8a, 0xd1, 0x20, 0x88, 0x0d, 0x24, 0xe2, 0x99, 0x02, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x44, 0x98, 0x3c, 0xd2, 0xb6, 0x00, 0x00, 0x00,
}
